#include "Disassembler.h"
#include "mem/constants.h"
#include "hash/xxhash.h"

namespace mem {
	InsnChunk InsnChunk::fromRange(uintptr_t startAddr, size_t maxBytes) {
		if (!m_insn || m_count == 0)
			return InsnChunk();

		uintptr_t endAddr = startAddr + maxBytes;

		int startIdx = -1, endIdx = -1;
		for (int i = 0; i < m_count; i++) {
			if (startIdx == -1 && m_insn[i].address >= startAddr)
				startIdx = i;
			if (m_insn[i].address < endAddr)
				endIdx = i;
			else break;
		}

		if (startIdx == -1 || endIdx == -1) {
			return InsnChunk();
		}

		int rangeCount = endIdx - startIdx + 1;
		cs_insn* newInsn = static_cast<cs_insn*>(cs_malloc(rangeCount));
		if (!newInsn)
			return InsnChunk();

		for (int i = 0; i < rangeCount; ++i) {
			newInsn[i] = m_insn[startIdx + i];
		}
		return InsnChunk(newInsn, rangeCount);
	}

	Disassembler::Disassembler(std::shared_ptr<mem::Memdump> memdump)
		: m_memdump{ memdump }
	{
		if (memdump) {
			if (memdump->getMeminfo()->is32Bit())
				m_mode = CS_MODE_32;
		}

		cs_err e = cs_open(m_arch, m_mode, &m_csh);
		if (e != CS_ERR_OK) {
			throw std::runtime_error("Failed to init capstone");
		}

		cs_option(m_csh, CS_OPT_SYNTAX, CS_OPT_SYNTAX_INTEL);
		cs_option(m_csh, CS_OPT_DETAIL, CS_OPT_ON);
	}

	/*
	Cases:
	1. We're disassembling executable memory, we deal directly with pages
	2. We're disassembling shellcode / dynamically generated bytecode, we deal with that seperately

	In either case, we
	1. Check the cache
	2. if cache, then compare the hash, if not then do everything from 0

	for page disassembly, we want to read a little under the page start, to account for potential cross-boundary instructions
	*/
	InsnChunk Disassembler::disassemble(uintptr_t address, size_t maxBytes) {
		if (m_pageCache.empty()) findExecutablePages();

		auto ctx = m_memdump->getRegionContext(reinterpret_cast<LPCVOID>(address));
		if (ctx.curr && ctx.curr->m_protection & mem::PAGE_EXECUTE_READ_FLAGS) { // handle disassembly for CachedPage
			uintptr_t pageStartAddr = reinterpret_cast<uintptr_t>(ctx.curr->m_original_addr);
			auto pageCache = getCacheFrom(m_pageCache, pageStartAddr);

			if (!pageCache) { // if for whatever reason we failed to get the cache just disassemble directly, though this shouldn't happen
				return disassembleRaw(address, maxBytes);
			}

			CachedPage& cache = pageCache.value().get();
			uintptr_t oldHash = cache.m_hash;

			hashMemory(cache);

			// memory didn't change, and we've disassembled before
			if (oldHash == cache.m_hash) {
				return cache.m_disassembly->fromRange(address, maxBytes);
			}

			// the hard case
			if (oldHash != cache.m_hash || !cache.m_disassembly.has_value()) {
				const size_t pageOverlap = 0x10;
				uintptr_t startAddr = pageStartAddr;
				size_t readBytes = cache.m_pRegion->m_size;

				if (ctx.prev && ctx.prev->m_protection & mem::PAGE_EXECUTE_READ_FLAGS) {
					startAddr = pageStartAddr - pageOverlap;
					readBytes += pageOverlap;
				}

				m_memdump->setLiveMode();
				mem::MemoryView mv = m_memdump->readBytesAt(
					reinterpret_cast<LPCVOID>(startAddr), readBytes);

				if (mv.size == 0)
					return InsnChunk();

				cs_insn* insn;
				size_t count = cs_disasm(m_csh, mv.data, mv.size, startAddr, 0, &insn);

				if (count == 0)
					return InsnChunk();

				std::vector<cs_insn> filteredInsns;
				uintptr_t pageEndAddr = pageStartAddr + cache.m_pRegion->m_size;

				for (int i = 0; i < count; ++i) {
					uintptr_t insnStart = insn[i].address;
					uintptr_t insnEnd = insnStart + insn[i].size;

					if (insnStart >= pageStartAddr && insnStart < pageEndAddr ||
						insnStart <  pageStartAddr && insnEnd > pageStartAddr) {
						filteredInsns.emplace_back(insn[i]);
					}
				}

				cs_free(insn, count);

				if (filteredInsns.empty())
					return InsnChunk();

				cs_insn* cachedInsns = static_cast<cs_insn*>(cs_malloc(filteredInsns.size()));
				if (!cachedInsns)
					return InsnChunk();

				for (size_t i = 0; i < filteredInsns.size(); ++i) {
					cachedInsns[i] = filteredInsns[i];
				}

				cache.m_disassembly = InsnChunk(cachedInsns, static_cast<int>(filteredInsns.size()));
			}
		}
		else if(ctx.curr) { // for shellcode and such we do direct disassembly because we assume the user knows what he's doing
			// check cache
			auto regionCache = getCacheFrom(m_regionCache, address);
			if (regionCache.has_value()) {
				CachedRegion& cache = regionCache.value();
				uintptr_t oldHash = cache.m_hash;

				hashMemory(cache);

				if (oldHash == cache.m_hash && cache.m_disassembly.has_value()) {
					return cache.m_disassembly->fromRange(address, maxBytes);
				}
			}

			InsnChunk result = disassembleRaw(address, maxBytes);
			if (!result.empty()) {
				CachedRegion newEntry{
					address,
					maxBytes,
					0,
					std::move(result)
				};

				hashMemory(newEntry);

				m_regionCache.emplace(address, std::move(newEntry));
				return m_regionCache[address].m_disassembly->fromRange(address, maxBytes);
			}

			return result;
		}

		return InsnChunk();
	}
	InsnChunk Disassembler::disassembleRaw(uintptr_t address, size_t maxBytes) {
		m_memdump->setLiveMode();
		mem::MemoryView mv = m_memdump->readBytesAt(reinterpret_cast<LPCVOID>(address), maxBytes);

		if (mv.size == 0)
			return InsnChunk();

		cs_insn* insn;
		size_t count = cs_disasm(m_csh, mv.data, mv.size, address, 0, &insn);

		if (count == 0)
			return InsnChunk();

		return InsnChunk(insn, static_cast<int>(count));
	}
	uintptr_t Disassembler::alignToInstrStart(uintptr_t address) {
		uintptr_t maxAddress = m_memdump->getMeminfo()->is32Bit()
			? mem::USERSPACE_END_32BIT
			: mem::USERSPACE_END_64BIT;

		if (address <= mem::PAGE_SIZE ||
			address >= (maxAddress & ~0xFFF))
			return address;

		const size_t maxLookback = 0x100;
		uintptr_t startAddress = (address > maxLookback) ? address - maxLookback : 0;
		size_t readBytes = address - startAddress + 0x10; // extra wiggle room

		// We just need to make sure that startAddress doesn't point to invalid memory or non-executable memory
		const RegionContext ctx = m_memdump->getRegionContext(reinterpret_cast<LPCVOID>(startAddress));
		if (ctx.curr == nullptr)
			startAddress = reinterpret_cast<uintptr_t>(ctx.next->m_original_addr);
		else if (!(ctx.curr->m_protection & mem::PAGE_EXECUTE_READ_FLAGS)) {
			return address;
		}

		m_memdump->setLiveMode();
		mem::MemoryView mv = m_memdump->readBytesAt(reinterpret_cast<LPCVOID>(startAddress), readBytes);

		if (mv.size == 0)
			return address;

		cs_insn* insn;
		size_t count = cs_disasm(m_csh, mv.data, mv.size, startAddress, 0, &insn);

		if (count == 0)
			return address;

		uintptr_t alignedAddress = address;
		for (int i = 0; i < count; ++i) {
			uintptr_t insnStart = insn[i].address;
			uintptr_t insnEnd = insnStart + insn[i].size;

			if (insnStart <= address && address < insnEnd) {
				alignedAddress = insnStart;
				break;
			}
			else if (insnStart > address) { // just in case there's some gap in between instructions
				if (i > 0) {
					alignedAddress = insn[i - 1].address;
				}
				break;
			}

			if (insnStart <= address) {
				alignedAddress = insnStart;
			}
		}

		cs_free(insn, count);
		return alignedAddress;
	}

	bool Disassembler::isJumpInstruction(const cs_insn* insn) const {
		return cs_insn_group(m_csh, insn, CS_GRP_JUMP);
	}
	bool Disassembler::isCallInstruction(const cs_insn* insn) const {
		return cs_insn_group(m_csh, insn, CS_GRP_CALL);
	}
	uintptr_t Disassembler::getJumpTarget(const cs_insn* insn) const {
		if (!cs_insn_group(m_csh, insn, CS_GRP_JUMP) && !cs_insn_group(m_csh, insn, CS_GRP_CALL))
			return 0;

		cs_detail* detail = insn->detail;
		if (!detail) return 0;

		for (int i = 0; i < detail->x86.op_count; ++i) {
			if (detail->x86.operands[i].type & X86_OP_IMM)
				return static_cast<uintptr_t>(detail->x86.operands[i].imm);
		}
		return 0;
	}

	const MemoryRegion* Disassembler::getExecutableRegion(uintptr_t address) const {
		const auto& region = m_memdump->getRegion(reinterpret_cast<LPCVOID>(address));
		if (region && (region->m_protection & mem::PAGE_EXECUTE_READ_FLAGS))
			return region;
		return nullptr;
	}

	void Disassembler::findExecutablePages() {
		m_memdump->dump(); // update memory
		std::vector<MEMORY_BASIC_INFORMATION> pages = m_memdump->getMeminfo()->getPages();

		for (const auto& mbi : pages) {
			if (mbi.State == MEM_COMMIT && (mbi.Protect & mem::PAGE_EXECUTE_READ_FLAGS)) {
				m_pageCache.emplace(reinterpret_cast<uintptr_t>(mbi.BaseAddress), CachedPage{
						0,
						m_memdump->getRegion(mbi.BaseAddress),
						std::optional<InsnChunk>{}
					});
			}
		}
	}
	void Disassembler::hashMemory(CachedPage& pageCache) {
		m_memdump->setLiveMode();

		mem::MemoryView mv = m_memdump->readBytesAt(
			reinterpret_cast<LPCVOID>(pageCache.m_pRegion->m_original_addr)
			, pageCache.m_pRegion->m_size);

		if (mv.size > 0) {
			uintptr_t xx3hash = XXH3_64bits(mv.data, mv.size);

			if (pageCache.m_hash != xx3hash) {
				pageCache.m_hash = xx3hash;
				pageCache.m_disassembly.reset();
			}
		}
	}
	void Disassembler::hashMemory(CachedRegion& regionCache) {
		m_memdump->setLiveMode();

		mem::MemoryView mv = m_memdump->readBytesAt(
			reinterpret_cast<LPCVOID>(regionCache.m_startAddr)
			, regionCache.m_size);

		if (mv.size > 0) {
			uintptr_t xx3hash = XXH3_64bits(mv.data, mv.size);

			if (regionCache.m_hash != xx3hash) {
				regionCache.m_hash = xx3hash;
				regionCache.m_disassembly.reset();
			}
		}
	}

	template<typename CacheMap>
	auto mem::Disassembler::getCacheFrom(CacheMap& cache, uintptr_t address)
		-> std::optional<std::reference_wrapper<typename CacheMap::mapped_type>> {
		auto it = cache.find(address);
		if (it != cache.end()) {
			return std::ref(it->second);
		}
		return std::nullopt;
	}
}