function(memutilz_enable_ipo target)
    if(MEMUTILZ_ENABLE_IPO)
        if(CMAKE_BUILD_TYPE STREQUAL "Debug")
            return()
        endif()

        include(CheckIPOSupported)
        check_ipo_supported(RESULT result OUTPUT output)
        if(result)
            set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
        else()
            message(STATUS "IPO not supported for ${target}: ${output}")
        endif()
    endif()
endfunction()