function(memutilz_enable_sanitizers target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "Target '${target}' does not exist!")
    endif()

    if(MEMUTILZ_ENABLE_SANITIZERS)
        find_package(Sanitizers)
        add_sanitizers("${target}")
    endif()
endfunction()
